use_frameworks!

target 'GlomexContentSdk_Example' do
  pod 'GlomexContentSdk', :path => '../'

  target 'GlomexContentSdk_Tests' do
    inherit! :search_paths

    pod 'Quick', :git => 'https://github.com/Quick/Quick.git'
    pod 'Nimble'
    pod 'OHHTTPStubs/Swift'
    pod 'OHHTTPStubs'
  end
end
