osx_image: xcode9.3
language: objective-c
podfile: Example/Podfile
xcode_workspace: ContentSDK

env:
  global:
  - FRAMEWORK_NAME=ContentSdk

before_install:
- gem install cocoapods
- pod repo update
- pod install --project-directory=Example
- pod install --project-directory=ContentSDK

script:
#Check code
- swiftlint
#Check podspec
- pod lib lint
#Unit tests
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace ContentSDK/ContentSDK.xcworkspace
  -scheme ContentSDK -destination 'platform=iOS Simulator,name=iPhone
  6s,OS=11.3' -sdk iphonesimulator11.3 ONLY_ACTIVE_ARCH=NO | xcpretty
#Build example
- set -o pipefail && xcodebuild -workspace Example/GlomexContentSdk.xcworkspace
  -scheme GlomexContentSdk-Example -destination 'platform=iOS Simulator,name=iPhone
  6s,OS=11.3' -sdk iphonesimulator11.3 ONLY_ACTIVE_ARCH=NO | xcpretty

before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME

deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_API_KEY}
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: glomex/content-sdk-ios
    tags: true
